export const AuthorActionTypes = {
  GET_ALL_AUTHORS: 'GET_ALL_AUTHORS',
  CREATE_AUTHOR: 'CREATE_AUTHOR',
  REMOVE_AUTHOR: 'REMOVE_AUTHOR',
  UPDATE_AUTHOR: 'UPDATE_AUTHOR',
  SET_AUTHOR_ERROR: 'SET_AUTHOR_ERROR',
  GET_SINGLE_AUTHOR: 'GET_SINGLE_AUTHOR',
  CREATE_AUTHOR: 'CREATE_AUTHOR',
  GET_BOOKS_FROM_AUTHOR: 'GET_BOOKS_FROM_AUTHOR',
  ADD_BOOK_TO_AUTHOR: 'ADD_BOOK_TO_AUTHOR',
  REMOVE_BOOK_FROM_AUTHOR: 'REMOVE_BOOK_FROM_AUTHOR',
};
