export const BookActionTypes = {
  GET_ALL_BOOKS: 'GET_ALL_BOOKS',
  CREATE_BOOK: 'CREATE_BOOK',
  REMOVE_BOOK: 'REMOVE_BOOK',
  UPDATE_BOOK: 'UPDATE_BOOK',
  SET_BOOK_ERROR: 'SET_BOOK_ERROR',
  GET_SINGLE_BOOK: 'GET_SINGLE_BOOK',
  CREATE_BOOK: 'CREATE_BOOK',
  GET_AUTHORS_FROM_BOOK: 'GET_AUTHORS_FROM_BOOK',
  ADD_AUTHOR_TO_BOOK: 'ADD_AUTHOR_TO_BOOK',
  REMOVE_AUTHOR_FROM_BOOK: 'REMOVE_AUTHOR_FROM_BOOK',
};
